#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Hand,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Auto,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
//                                  Teleop                                           //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "AvoidWierd.h"

//***********************************************************//
//                      Global Variables                     //
//***********************************************************//

int maxHandValue = 250;
int minHandValue = 20;

//***********************************************************//
//                         Methods                           //
//***********************************************************//
void all_stop()
{
	motor[Left] = 0;
	motor[Right] = 0;
}
void drive(int left_motor,int right_motor)
{
	int maxVal = 60;

	int leftVal = returnValueMotor(left_motor, maxVal);
	int rightVal = returnValueMotor(right_motor, maxVal);

	motor[Left] = leftVal;
	motor[Right] = rightVal;
}

void shoulderMovement(int ycord)
{
	int maxVal = 60;
	motor[Arm] = returnValueMotor(ycord, maxVal);
	return;
}

void handMovement(int ycord)
{
	int maxVal = 60;
	motor[Hand] = returnValueMotor(ycord, maxVal);
	return;
}
void handMovement_2(int dPad)
{
	int currentPosition = ServoValue[Auto];
	int newPosition = currentPosition;

	if (dPad == 0)
	{
		if ((currentPosition + 1) < maxHandValue)
		{
			newPosition = currentPosition + 1;
		}
	}
	else if (dPad == 4)
	{
		if ((currentPosition - 1) > minHandValue)
		{
			newPosition = currentPosition - 1;
		}
	}
	servo[Auto] = newPosition;
}

/*
void flag_raise(int flag_power)
{
int maxVal = 50;
motor[Flag] = returnValueMotor(flag_power, maxVal);
return;
}
*/

//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
	waitForStart();

	while (true)
	{
		getJoystickSettings(joystick);
		servo[Auto] = 150;
		//driver controls
		int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
		//int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1
		int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20); //y coordinate for the right joystick on controller 1
		//arm/hand controls
		//int cont2_right_yval = avoidWeird(joystick.joy2_y2, 20);
		//int cont2_left_yval = avoidWeird(joystick.joy2_y1, 20);
		//int cont1_dPad = joystick.joy1_TopHat; //Value of the dPad for controller 2

		//drive(cont1_left_yval, cont1_right_yval);
		//shoulderMovement(cont2_right_yval);
		//handMovement(cont2_left_yval);
		//flag_raise(cont1_right_yval);
		//int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
		//int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1
		int cont2_right_yval = avoidWeird(joystick.joy2_y2, 20);
		int cont2_dPad = joystick.joy2_TopHat; //Value of the dPad for controller 2
		int cont2_left_yval = avoidWeird(joystick.joy2_y1, 20);

		//drive(cont1_left_yval, cont1_right_xval);
		shoulderMovement(cont2_right_yval);
		handMovement_2(cont2_dPad);
		handMovement(cont2_left_yval);
		drive(cont1_left_yval, cont1_right_yval);

		while (joy2Btn(5) == 1)
		{
			motor [Flag] = 75;
		}
		while (joy2Btn(7) == 1)
		{
			motor [Flag] = -75;
		}
		while (joy2Btn(6) ==1)
		{
			motor [Flag] = 0;
		}

	}
}
