#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Hand,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//The above lines describe the configuration of the motors, servos, and sensors used on the robot. In this instance there is a motor for each side
//of the robot, along with one for the arm. There is also a servo that is for the hand. No sensors are included.
///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
//                                  Teleop                                           //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages. Do not remove!!
#include "AvoidWierd.h" //This file adds in a greater deadzone to the controlers in order to keep the motors safe. Do not remove!!

//***********************************************************//
//                       Variables                           //
//***********************************************************//

int maxHandValue = 250;
int minHandValue = 20;

//***********************************************************//
//                         Methods                           //
//***********************************************************//
void all_stop()
{
	motor[Left] = 0;
	motor[Right] = 0;
}
void drive(int ycord,int xcord)
{
	int maxVal = 40;
	int turningVal = returnValueMotor(xcord, maxVal);
	int motorVal = returnValueMotor(ycord, maxVal);

	motor[Left] = motorVal - (2*turningVal);

	motor[Right] = motorVal + (2*turningVal);
}

void shoulderMovement(int ycord)
{
	if (ycord > 0)
	{
		int maxVal = 70;
		motor[Arm] = returnValueMotor(ycord, maxVal);
		return;
	}

	else
	{
		int maxVal = 70;
		motor[Arm] = returnValueMotor(ycord, maxVal);
		return;
	}
}

void handMovement(int dPad)
{
	int currentPosition = ServoValue[Auto];
	int newPosition = currentPosition;

	if (dPad == 0)
	{
		if ((currentPosition + 1) < maxHandValue)
		{
			newPosition = currentPosition + 1;
		}
	}
	else if (dPad == 4)
	{
		if ((currentPosition - 1) > minHandValue)
		{
			newPosition = currentPosition - 1;
		}
	}
	servo[Auto] = newPosition;
}



//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
	waitForStart();

	while (true)
	{
		getJoystickSettings(joystick);
		int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
		int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1
		int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20);
		int cont1_dPad = joystick.joy1_TopHat; //Value of the dPad for controller 2

		drive(cont1_left_yval, cont1_left_xval);
		shoulderMovement(cont1_right_yval);
		handMovement(cont1_dPad);

		if (joy1Btn(3) == 1)
		{
			servo[Hand] = 60;
		}
		if (joy1Btn(1) == 1)
		{
			servo[Hand] = 30;
		}
//The statements above dictate servo movement. They say that if button 3 and 1 on joystick 1 are pressed,\
//then the servo will move. The 30 and 60 are the degrees that the servo will move. The degrees number must be between 0 and 180.
//


	}
}
